site_name: Case - Folks

extra_css:
  - css/custom.css

theme:

  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.indexes
    - navigation.prune

    

repo_url: https://github.com/CaioDuart3/Folks_case
repo_name: GitHub

nav:
  - Apresentação : index.md
  - Documento de Arquitetura: arch.md
